allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vitest: 4.1.10
  vite-plus: 0.2.4
  "@vitest/browser-playwright": 4.1.10
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
