/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as FlagRouteImport } from './routes/flag'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RelationsIndexRouteImport } from './routes/relations/index'
import { Route as PronunciationIndexRouteImport } from './routes/pronunciation/index'
import { Route as NumbersIndexRouteImport } from './routes/numbers/index'
import { Route as GrammarIndexRouteImport } from './routes/grammar/index'
import { Route as DictationIndexRouteImport } from './routes/dictation/index'
import { Route as ConversationIndexRouteImport } from './routes/conversation/index'
import { Route as RelationsPronounsRouteImport } from './routes/relations/pronouns'
import { Route as RelationsPracticeRouteImport } from './routes/relations/practice'
import { Route as PronunciationVowelsRouteImport } from './routes/pronunciation/vowels'
import { Route as PronunciationTonesVowelRouteImport } from './routes/pronunciation/tones-vowel'
import { Route as PronunciationTonesRouteImport } from './routes/pronunciation/tones'
import { Route as PronunciationPracticeRouteImport } from './routes/pronunciation/practice'
import { Route as PronunciationDoubleVowelsRouteImport } from './routes/pronunciation/double-vowels'
import { Route as PronunciationConsonantsRouteImport } from './routes/pronunciation/consonants'
import { Route as NumbersTimeRouteImport } from './routes/numbers/time'
import { Route as NumbersPracticeRouteImport } from './routes/numbers/practice'
import { Route as NumbersDatesRouteImport } from './routes/numbers/dates'
import { Route as NumbersCountingRouteImport } from './routes/numbers/counting'
import { Route as GrammarWordOrderRouteImport } from './routes/grammar/word-order'
import { Route as GrammarTensesRouteImport } from './routes/grammar/tenses'
import { Route as GrammarSentenceStructureRouteImport } from './routes/grammar/sentence-structure'
import { Route as GrammarQuestionsRouteImport } from './routes/grammar/questions'
import { Route as GrammarNegativesRouteImport } from './routes/grammar/negatives'
import { Route as GrammarFocusMarkersRouteImport } from './routes/grammar/focus-markers'
import { Route as GrammarExclamationsRouteImport } from './routes/grammar/exclamations'
import { Route as GrammarDemonstrativesRouteImport } from './routes/grammar/demonstratives'
import { Route as GrammarConditionalsRouteImport } from './routes/grammar/conditionals'
import { Route as GrammarCommandsRouteImport } from './routes/grammar/commands'
import { Route as GrammarClassifiersRouteImport } from './routes/grammar/classifiers'
import { Route as DictationSpeakSlugRouteImport } from './routes/dictation/speak.$slug'
import { Route as DictationListenSlugRouteImport } from './routes/dictation/listen.$slug'

const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagRoute = FlagRouteImport.update({
  id: '/flag',
  path: '/flag',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationsIndexRoute = RelationsIndexRouteImport.update({
  id: '/relations/',
  path: '/relations/',
  getParentRoute: () => rootRouteImport,
} as any)
const PronunciationIndexRoute = PronunciationIndexRouteImport.update({
  id: '/pronunciation/',
  path: '/pronunciation/',
  getParentRoute: () => rootRouteImport,
} as any)
const NumbersIndexRoute = NumbersIndexRouteImport.update({
  id: '/numbers/',
  path: '/numbers/',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarIndexRoute = GrammarIndexRouteImport.update({
  id: '/grammar/',
  path: '/grammar/',
  getParentRoute: () => rootRouteImport,
} as any)
const DictationIndexRoute = DictationIndexRouteImport.update({
  id: '/dictation/',
  path: '/dictation/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationIndexRoute = ConversationIndexRouteImport.update({
  id: '/conversation/',
  path: '/conversation/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationsPronounsRoute = RelationsPronounsRouteImport.update({
  id: '/relations/pronouns',
  path: '/relations/pronouns',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationsPracticeRoute = RelationsPracticeRouteImport.update({
  id: '/relations/practice',
  path: '/relations/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PronunciationVowelsRoute = PronunciationVowelsRouteImport.update({
  id: '/pronunciation/vowels',
  path: '/pronunciation/vowels',
  getParentRoute: () => rootRouteImport,
} as any)
const PronunciationTonesVowelRoute = PronunciationTonesVowelRouteImport.update({
  id: '/pronunciation/tones-vowel',
  path: '/pronunciation/tones-vowel',
  getParentRoute: () => rootRouteImport,
} as any)
const PronunciationTonesRoute = PronunciationTonesRouteImport.update({
  id: '/pronunciation/tones',
  path: '/pronunciation/tones',
  getParentRoute: () => rootRouteImport,
} as any)
const PronunciationPracticeRoute = PronunciationPracticeRouteImport.update({
  id: '/pronunciation/practice',
  path: '/pronunciation/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PronunciationDoubleVowelsRoute =
  PronunciationDoubleVowelsRouteImport.update({
    id: '/pronunciation/double-vowels',
    path: '/pronunciation/double-vowels',
    getParentRoute: () => rootRouteImport,
  } as any)
const PronunciationConsonantsRoute = PronunciationConsonantsRouteImport.update({
  id: '/pronunciation/consonants',
  path: '/pronunciation/consonants',
  getParentRoute: () => rootRouteImport,
} as any)
const NumbersTimeRoute = NumbersTimeRouteImport.update({
  id: '/numbers/time',
  path: '/numbers/time',
  getParentRoute: () => rootRouteImport,
} as any)
const NumbersPracticeRoute = NumbersPracticeRouteImport.update({
  id: '/numbers/practice',
  path: '/numbers/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const NumbersDatesRoute = NumbersDatesRouteImport.update({
  id: '/numbers/dates',
  path: '/numbers/dates',
  getParentRoute: () => rootRouteImport,
} as any)
const NumbersCountingRoute = NumbersCountingRouteImport.update({
  id: '/numbers/counting',
  path: '/numbers/counting',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarWordOrderRoute = GrammarWordOrderRouteImport.update({
  id: '/grammar/word-order',
  path: '/grammar/word-order',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarTensesRoute = GrammarTensesRouteImport.update({
  id: '/grammar/tenses',
  path: '/grammar/tenses',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarSentenceStructureRoute =
  GrammarSentenceStructureRouteImport.update({
    id: '/grammar/sentence-structure',
    path: '/grammar/sentence-structure',
    getParentRoute: () => rootRouteImport,
  } as any)
const GrammarQuestionsRoute = GrammarQuestionsRouteImport.update({
  id: '/grammar/questions',
  path: '/grammar/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarNegativesRoute = GrammarNegativesRouteImport.update({
  id: '/grammar/negatives',
  path: '/grammar/negatives',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarFocusMarkersRoute = GrammarFocusMarkersRouteImport.update({
  id: '/grammar/focus-markers',
  path: '/grammar/focus-markers',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarExclamationsRoute = GrammarExclamationsRouteImport.update({
  id: '/grammar/exclamations',
  path: '/grammar/exclamations',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarDemonstrativesRoute = GrammarDemonstrativesRouteImport.update({
  id: '/grammar/demonstratives',
  path: '/grammar/demonstratives',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarConditionalsRoute = GrammarConditionalsRouteImport.update({
  id: '/grammar/conditionals',
  path: '/grammar/conditionals',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarCommandsRoute = GrammarCommandsRouteImport.update({
  id: '/grammar/commands',
  path: '/grammar/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const GrammarClassifiersRoute = GrammarClassifiersRouteImport.update({
  id: '/grammar/classifiers',
  path: '/grammar/classifiers',
  getParentRoute: () => rootRouteImport,
} as any)
const DictationSpeakSlugRoute = DictationSpeakSlugRouteImport.update({
  id: '/dictation/speak/$slug',
  path: '/dictation/speak/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DictationListenSlugRoute = DictationListenSlugRouteImport.update({
  id: '/dictation/listen/$slug',
  path: '/dictation/listen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/flag': typeof FlagRoute
  '/showcase': typeof ShowcaseRoute
  '/grammar/classifiers': typeof GrammarClassifiersRoute
  '/grammar/commands': typeof GrammarCommandsRoute
  '/grammar/conditionals': typeof GrammarConditionalsRoute
  '/grammar/demonstratives': typeof GrammarDemonstrativesRoute
  '/grammar/exclamations': typeof GrammarExclamationsRoute
  '/grammar/focus-markers': typeof GrammarFocusMarkersRoute
  '/grammar/negatives': typeof GrammarNegativesRoute
  '/grammar/questions': typeof GrammarQuestionsRoute
  '/grammar/sentence-structure': typeof GrammarSentenceStructureRoute
  '/grammar/tenses': typeof GrammarTensesRoute
  '/grammar/word-order': typeof GrammarWordOrderRoute
  '/numbers/counting': typeof NumbersCountingRoute
  '/numbers/dates': typeof NumbersDatesRoute
  '/numbers/practice': typeof NumbersPracticeRoute
  '/numbers/time': typeof NumbersTimeRoute
  '/pronunciation/consonants': typeof PronunciationConsonantsRoute
  '/pronunciation/double-vowels': typeof PronunciationDoubleVowelsRoute
  '/pronunciation/practice': typeof PronunciationPracticeRoute
  '/pronunciation/tones': typeof PronunciationTonesRoute
  '/pronunciation/tones-vowel': typeof PronunciationTonesVowelRoute
  '/pronunciation/vowels': typeof PronunciationVowelsRoute
  '/relations/practice': typeof RelationsPracticeRoute
  '/relations/pronouns': typeof RelationsPronounsRoute
  '/conversation': typeof ConversationIndexRoute
  '/dictation': typeof DictationIndexRoute
  '/grammar': typeof GrammarIndexRoute
  '/numbers': typeof NumbersIndexRoute
  '/pronunciation': typeof PronunciationIndexRoute
  '/relations': typeof RelationsIndexRoute
  '/dictation/listen/$slug': typeof DictationListenSlugRoute
  '/dictation/speak/$slug': typeof DictationSpeakSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/flag': typeof FlagRoute
  '/showcase': typeof ShowcaseRoute
  '/grammar/classifiers': typeof GrammarClassifiersRoute
  '/grammar/commands': typeof GrammarCommandsRoute
  '/grammar/conditionals': typeof GrammarConditionalsRoute
  '/grammar/demonstratives': typeof GrammarDemonstrativesRoute
  '/grammar/exclamations': typeof GrammarExclamationsRoute
  '/grammar/focus-markers': typeof GrammarFocusMarkersRoute
  '/grammar/negatives': typeof GrammarNegativesRoute
  '/grammar/questions': typeof GrammarQuestionsRoute
  '/grammar/sentence-structure': typeof GrammarSentenceStructureRoute
  '/grammar/tenses': typeof GrammarTensesRoute
  '/grammar/word-order': typeof GrammarWordOrderRoute
  '/numbers/counting': typeof NumbersCountingRoute
  '/numbers/dates': typeof NumbersDatesRoute
  '/numbers/practice': typeof NumbersPracticeRoute
  '/numbers/time': typeof NumbersTimeRoute
  '/pronunciation/consonants': typeof PronunciationConsonantsRoute
  '/pronunciation/double-vowels': typeof PronunciationDoubleVowelsRoute
  '/pronunciation/practice': typeof PronunciationPracticeRoute
  '/pronunciation/tones': typeof PronunciationTonesRoute
  '/pronunciation/tones-vowel': typeof PronunciationTonesVowelRoute
  '/pronunciation/vowels': typeof PronunciationVowelsRoute
  '/relations/practice': typeof RelationsPracticeRoute
  '/relations/pronouns': typeof RelationsPronounsRoute
  '/conversation': typeof ConversationIndexRoute
  '/dictation': typeof DictationIndexRoute
  '/grammar': typeof GrammarIndexRoute
  '/numbers': typeof NumbersIndexRoute
  '/pronunciation': typeof PronunciationIndexRoute
  '/relations': typeof RelationsIndexRoute
  '/dictation/listen/$slug': typeof DictationListenSlugRoute
  '/dictation/speak/$slug': typeof DictationSpeakSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/flag': typeof FlagRoute
  '/showcase': typeof ShowcaseRoute
  '/grammar/classifiers': typeof GrammarClassifiersRoute
  '/grammar/commands': typeof GrammarCommandsRoute
  '/grammar/conditionals': typeof GrammarConditionalsRoute
  '/grammar/demonstratives': typeof GrammarDemonstrativesRoute
  '/grammar/exclamations': typeof GrammarExclamationsRoute
  '/grammar/focus-markers': typeof GrammarFocusMarkersRoute
  '/grammar/negatives': typeof GrammarNegativesRoute
  '/grammar/questions': typeof GrammarQuestionsRoute
  '/grammar/sentence-structure': typeof GrammarSentenceStructureRoute
  '/grammar/tenses': typeof GrammarTensesRoute
  '/grammar/word-order': typeof GrammarWordOrderRoute
  '/numbers/counting': typeof NumbersCountingRoute
  '/numbers/dates': typeof NumbersDatesRoute
  '/numbers/practice': typeof NumbersPracticeRoute
  '/numbers/time': typeof NumbersTimeRoute
  '/pronunciation/consonants': typeof PronunciationConsonantsRoute
  '/pronunciation/double-vowels': typeof PronunciationDoubleVowelsRoute
  '/pronunciation/practice': typeof PronunciationPracticeRoute
  '/pronunciation/tones': typeof PronunciationTonesRoute
  '/pronunciation/tones-vowel': typeof PronunciationTonesVowelRoute
  '/pronunciation/vowels': typeof PronunciationVowelsRoute
  '/relations/practice': typeof RelationsPracticeRoute
  '/relations/pronouns': typeof RelationsPronounsRoute
  '/conversation/': typeof ConversationIndexRoute
  '/dictation/': typeof DictationIndexRoute
  '/grammar/': typeof GrammarIndexRoute
  '/numbers/': typeof NumbersIndexRoute
  '/pronunciation/': typeof PronunciationIndexRoute
  '/relations/': typeof RelationsIndexRoute
  '/dictation/listen/$slug': typeof DictationListenSlugRoute
  '/dictation/speak/$slug': typeof DictationSpeakSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/flag'
    | '/showcase'
    | '/grammar/classifiers'
    | '/grammar/commands'
    | '/grammar/conditionals'
    | '/grammar/demonstratives'
    | '/grammar/exclamations'
    | '/grammar/focus-markers'
    | '/grammar/negatives'
    | '/grammar/questions'
    | '/grammar/sentence-structure'
    | '/grammar/tenses'
    | '/grammar/word-order'
    | '/numbers/counting'
    | '/numbers/dates'
    | '/numbers/practice'
    | '/numbers/time'
    | '/pronunciation/consonants'
    | '/pronunciation/double-vowels'
    | '/pronunciation/practice'
    | '/pronunciation/tones'
    | '/pronunciation/tones-vowel'
    | '/pronunciation/vowels'
    | '/relations/practice'
    | '/relations/pronouns'
    | '/conversation'
    | '/dictation'
    | '/grammar'
    | '/numbers'
    | '/pronunciation'
    | '/relations'
    | '/dictation/listen/$slug'
    | '/dictation/speak/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/flag'
    | '/showcase'
    | '/grammar/classifiers'
    | '/grammar/commands'
    | '/grammar/conditionals'
    | '/grammar/demonstratives'
    | '/grammar/exclamations'
    | '/grammar/focus-markers'
    | '/grammar/negatives'
    | '/grammar/questions'
    | '/grammar/sentence-structure'
    | '/grammar/tenses'
    | '/grammar/word-order'
    | '/numbers/counting'
    | '/numbers/dates'
    | '/numbers/practice'
    | '/numbers/time'
    | '/pronunciation/consonants'
    | '/pronunciation/double-vowels'
    | '/pronunciation/practice'
    | '/pronunciation/tones'
    | '/pronunciation/tones-vowel'
    | '/pronunciation/vowels'
    | '/relations/practice'
    | '/relations/pronouns'
    | '/conversation'
    | '/dictation'
    | '/grammar'
    | '/numbers'
    | '/pronunciation'
    | '/relations'
    | '/dictation/listen/$slug'
    | '/dictation/speak/$slug'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/flag'
    | '/showcase'
    | '/grammar/classifiers'
    | '/grammar/commands'
    | '/grammar/conditionals'
    | '/grammar/demonstratives'
    | '/grammar/exclamations'
    | '/grammar/focus-markers'
    | '/grammar/negatives'
    | '/grammar/questions'
    | '/grammar/sentence-structure'
    | '/grammar/tenses'
    | '/grammar/word-order'
    | '/numbers/counting'
    | '/numbers/dates'
    | '/numbers/practice'
    | '/numbers/time'
    | '/pronunciation/consonants'
    | '/pronunciation/double-vowels'
    | '/pronunciation/practice'
    | '/pronunciation/tones'
    | '/pronunciation/tones-vowel'
    | '/pronunciation/vowels'
    | '/relations/practice'
    | '/relations/pronouns'
    | '/conversation/'
    | '/dictation/'
    | '/grammar/'
    | '/numbers/'
    | '/pronunciation/'
    | '/relations/'
    | '/dictation/listen/$slug'
    | '/dictation/speak/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  FlagRoute: typeof FlagRoute
  ShowcaseRoute: typeof ShowcaseRoute
  GrammarClassifiersRoute: typeof GrammarClassifiersRoute
  GrammarCommandsRoute: typeof GrammarCommandsRoute
  GrammarConditionalsRoute: typeof GrammarConditionalsRoute
  GrammarDemonstrativesRoute: typeof GrammarDemonstrativesRoute
  GrammarExclamationsRoute: typeof GrammarExclamationsRoute
  GrammarFocusMarkersRoute: typeof GrammarFocusMarkersRoute
  GrammarNegativesRoute: typeof GrammarNegativesRoute
  GrammarQuestionsRoute: typeof GrammarQuestionsRoute
  GrammarSentenceStructureRoute: typeof GrammarSentenceStructureRoute
  GrammarTensesRoute: typeof GrammarTensesRoute
  GrammarWordOrderRoute: typeof GrammarWordOrderRoute
  NumbersCountingRoute: typeof NumbersCountingRoute
  NumbersDatesRoute: typeof NumbersDatesRoute
  NumbersPracticeRoute: typeof NumbersPracticeRoute
  NumbersTimeRoute: typeof NumbersTimeRoute
  PronunciationConsonantsRoute: typeof PronunciationConsonantsRoute
  PronunciationDoubleVowelsRoute: typeof PronunciationDoubleVowelsRoute
  PronunciationPracticeRoute: typeof PronunciationPracticeRoute
  PronunciationTonesRoute: typeof PronunciationTonesRoute
  PronunciationTonesVowelRoute: typeof PronunciationTonesVowelRoute
  PronunciationVowelsRoute: typeof PronunciationVowelsRoute
  RelationsPracticeRoute: typeof RelationsPracticeRoute
  RelationsPronounsRoute: typeof RelationsPronounsRoute
  ConversationIndexRoute: typeof ConversationIndexRoute
  DictationIndexRoute: typeof DictationIndexRoute
  GrammarIndexRoute: typeof GrammarIndexRoute
  NumbersIndexRoute: typeof NumbersIndexRoute
  PronunciationIndexRoute: typeof PronunciationIndexRoute
  RelationsIndexRoute: typeof RelationsIndexRoute
  DictationListenSlugRoute: typeof DictationListenSlugRoute
  DictationSpeakSlugRoute: typeof DictationSpeakSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flag': {
      id: '/flag'
      path: '/flag'
      fullPath: '/flag'
      preLoaderRoute: typeof FlagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relations/': {
      id: '/relations/'
      path: '/relations'
      fullPath: '/relations'
      preLoaderRoute: typeof RelationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronunciation/': {
      id: '/pronunciation/'
      path: '/pronunciation'
      fullPath: '/pronunciation'
      preLoaderRoute: typeof PronunciationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numbers/': {
      id: '/numbers/'
      path: '/numbers'
      fullPath: '/numbers'
      preLoaderRoute: typeof NumbersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/': {
      id: '/grammar/'
      path: '/grammar'
      fullPath: '/grammar'
      preLoaderRoute: typeof GrammarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictation/': {
      id: '/dictation/'
      path: '/dictation'
      fullPath: '/dictation'
      preLoaderRoute: typeof DictationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversation/': {
      id: '/conversation/'
      path: '/conversation'
      fullPath: '/conversation'
      preLoaderRoute: typeof ConversationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relations/pronouns': {
      id: '/relations/pronouns'
      path: '/relations/pronouns'
      fullPath: '/relations/pronouns'
      preLoaderRoute: typeof RelationsPronounsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relations/practice': {
      id: '/relations/practice'
      path: '/relations/practice'
      fullPath: '/relations/practice'
      preLoaderRoute: typeof RelationsPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronunciation/vowels': {
      id: '/pronunciation/vowels'
      path: '/pronunciation/vowels'
      fullPath: '/pronunciation/vowels'
      preLoaderRoute: typeof PronunciationVowelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronunciation/tones-vowel': {
      id: '/pronunciation/tones-vowel'
      path: '/pronunciation/tones-vowel'
      fullPath: '/pronunciation/tones-vowel'
      preLoaderRoute: typeof PronunciationTonesVowelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronunciation/tones': {
      id: '/pronunciation/tones'
      path: '/pronunciation/tones'
      fullPath: '/pronunciation/tones'
      preLoaderRoute: typeof PronunciationTonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronunciation/practice': {
      id: '/pronunciation/practice'
      path: '/pronunciation/practice'
      fullPath: '/pronunciation/practice'
      preLoaderRoute: typeof PronunciationPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronunciation/double-vowels': {
      id: '/pronunciation/double-vowels'
      path: '/pronunciation/double-vowels'
      fullPath: '/pronunciation/double-vowels'
      preLoaderRoute: typeof PronunciationDoubleVowelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pronunciation/consonants': {
      id: '/pronunciation/consonants'
      path: '/pronunciation/consonants'
      fullPath: '/pronunciation/consonants'
      preLoaderRoute: typeof PronunciationConsonantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numbers/time': {
      id: '/numbers/time'
      path: '/numbers/time'
      fullPath: '/numbers/time'
      preLoaderRoute: typeof NumbersTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numbers/practice': {
      id: '/numbers/practice'
      path: '/numbers/practice'
      fullPath: '/numbers/practice'
      preLoaderRoute: typeof NumbersPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numbers/dates': {
      id: '/numbers/dates'
      path: '/numbers/dates'
      fullPath: '/numbers/dates'
      preLoaderRoute: typeof NumbersDatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numbers/counting': {
      id: '/numbers/counting'
      path: '/numbers/counting'
      fullPath: '/numbers/counting'
      preLoaderRoute: typeof NumbersCountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/word-order': {
      id: '/grammar/word-order'
      path: '/grammar/word-order'
      fullPath: '/grammar/word-order'
      preLoaderRoute: typeof GrammarWordOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/tenses': {
      id: '/grammar/tenses'
      path: '/grammar/tenses'
      fullPath: '/grammar/tenses'
      preLoaderRoute: typeof GrammarTensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/sentence-structure': {
      id: '/grammar/sentence-structure'
      path: '/grammar/sentence-structure'
      fullPath: '/grammar/sentence-structure'
      preLoaderRoute: typeof GrammarSentenceStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/questions': {
      id: '/grammar/questions'
      path: '/grammar/questions'
      fullPath: '/grammar/questions'
      preLoaderRoute: typeof GrammarQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/negatives': {
      id: '/grammar/negatives'
      path: '/grammar/negatives'
      fullPath: '/grammar/negatives'
      preLoaderRoute: typeof GrammarNegativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/focus-markers': {
      id: '/grammar/focus-markers'
      path: '/grammar/focus-markers'
      fullPath: '/grammar/focus-markers'
      preLoaderRoute: typeof GrammarFocusMarkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/exclamations': {
      id: '/grammar/exclamations'
      path: '/grammar/exclamations'
      fullPath: '/grammar/exclamations'
      preLoaderRoute: typeof GrammarExclamationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/demonstratives': {
      id: '/grammar/demonstratives'
      path: '/grammar/demonstratives'
      fullPath: '/grammar/demonstratives'
      preLoaderRoute: typeof GrammarDemonstrativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/conditionals': {
      id: '/grammar/conditionals'
      path: '/grammar/conditionals'
      fullPath: '/grammar/conditionals'
      preLoaderRoute: typeof GrammarConditionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/commands': {
      id: '/grammar/commands'
      path: '/grammar/commands'
      fullPath: '/grammar/commands'
      preLoaderRoute: typeof GrammarCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grammar/classifiers': {
      id: '/grammar/classifiers'
      path: '/grammar/classifiers'
      fullPath: '/grammar/classifiers'
      preLoaderRoute: typeof GrammarClassifiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictation/speak/$slug': {
      id: '/dictation/speak/$slug'
      path: '/dictation/speak/$slug'
      fullPath: '/dictation/speak/$slug'
      preLoaderRoute: typeof DictationSpeakSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictation/listen/$slug': {
      id: '/dictation/listen/$slug'
      path: '/dictation/listen/$slug'
      fullPath: '/dictation/listen/$slug'
      preLoaderRoute: typeof DictationListenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  FlagRoute: FlagRoute,
  ShowcaseRoute: ShowcaseRoute,
  GrammarClassifiersRoute: GrammarClassifiersRoute,
  GrammarCommandsRoute: GrammarCommandsRoute,
  GrammarConditionalsRoute: GrammarConditionalsRoute,
  GrammarDemonstrativesRoute: GrammarDemonstrativesRoute,
  GrammarExclamationsRoute: GrammarExclamationsRoute,
  GrammarFocusMarkersRoute: GrammarFocusMarkersRoute,
  GrammarNegativesRoute: GrammarNegativesRoute,
  GrammarQuestionsRoute: GrammarQuestionsRoute,
  GrammarSentenceStructureRoute: GrammarSentenceStructureRoute,
  GrammarTensesRoute: GrammarTensesRoute,
  GrammarWordOrderRoute: GrammarWordOrderRoute,
  NumbersCountingRoute: NumbersCountingRoute,
  NumbersDatesRoute: NumbersDatesRoute,
  NumbersPracticeRoute: NumbersPracticeRoute,
  NumbersTimeRoute: NumbersTimeRoute,
  PronunciationConsonantsRoute: PronunciationConsonantsRoute,
  PronunciationDoubleVowelsRoute: PronunciationDoubleVowelsRoute,
  PronunciationPracticeRoute: PronunciationPracticeRoute,
  PronunciationTonesRoute: PronunciationTonesRoute,
  PronunciationTonesVowelRoute: PronunciationTonesVowelRoute,
  PronunciationVowelsRoute: PronunciationVowelsRoute,
  RelationsPracticeRoute: RelationsPracticeRoute,
  RelationsPronounsRoute: RelationsPronounsRoute,
  ConversationIndexRoute: ConversationIndexRoute,
  DictationIndexRoute: DictationIndexRoute,
  GrammarIndexRoute: GrammarIndexRoute,
  NumbersIndexRoute: NumbersIndexRoute,
  PronunciationIndexRoute: PronunciationIndexRoute,
  RelationsIndexRoute: RelationsIndexRoute,
  DictationListenSlugRoute: DictationListenSlugRoute,
  DictationSpeakSlugRoute: DictationSpeakSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
